# Generated by Django 4.2.6 on 2023-10-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='from_base',
        ),
        migrations.RemoveField(
            model_name='review',
            name='from_base',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='from_base',
        ),
    ]
